<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.6 on win32)" generated="20200714 22:11:53.578" rpa="false">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="Sinamope" source="C:\TEST_SINAMOPE\TEST\sinamope.robot">
<test id="s1-s1-t1" name="CC001 SINAMOPE (SISTEMA SINAMOPE)(DESCARGAR REPORTE PDF)">
<kw name="No Operation" library="BuiltIn">
<doc>Does absolutely nothing.</doc>
<status status="NOT_RUN" starttime="20200714 22:11:54.788" endtime="20200714 22:11:54.788"></status>
</kw>
<doc>PRUEBA SINAMOPE 001 (DESCARGAR REPORTE PDF)</doc>
<tags>
<tag>s001</tag>
</tags>
<status status="PASS" starttime="20200714 22:11:54.788" endtime="20200714 22:11:54.788" critical="yes"></status>
</test>
<doc>Casos de Prueba Proyecto SINAMOPE</doc>
<status status="PASS" starttime="20200714 22:11:53.599" endtime="20200714 22:11:54.788"></status>
</suite>
<suite id="s1-s2" name="Sinamope2" source="C:\TEST_SINAMOPE\TEST\sinamope2.robot">
<test id="s1-s2-t1" name="CC001 SINAMOPE (SISTEMA SINAMOPE)(DESCARGAR REPORTE PDF)">
<kw name="No Operation" library="BuiltIn">
<doc>Does absolutely nothing.</doc>
<status status="NOT_RUN" starttime="20200714 22:11:54.804" endtime="20200714 22:11:54.804"></status>
</kw>
<doc>PRUEBA SINAMOPE 001 (DESCARGAR REPORTE PDF)</doc>
<tags>
<tag>s001</tag>
</tags>
<status status="PASS" starttime="20200714 22:11:54.803" endtime="20200714 22:11:54.804" critical="yes"></status>
</test>
<doc>Casos de Prueba Proyecto SINAMOPE</doc>
<status status="PASS" starttime="20200714 22:11:54.788" endtime="20200714 22:11:54.805"></status>
</suite>
<suite id="s1-s3" name="Sinamope3" source="C:\TEST_SINAMOPE\TEST\sinamope3.robot">
<test id="s1-s3-t1" name="CC001 SINAMOPE (SISTEMA SINAMOPE)(DESCARGAR REPORTE PDF)">
<kw name="No Operation" library="BuiltIn">
<doc>Does absolutely nothing.</doc>
<status status="NOT_RUN" starttime="20200714 22:11:54.820" endtime="20200714 22:11:54.821"></status>
</kw>
<doc>PRUEBA SINAMOPE 001 (DESCARGAR REPORTE PDF)</doc>
<tags>
<tag>s001</tag>
</tags>
<status status="PASS" starttime="20200714 22:11:54.820" endtime="20200714 22:11:54.821" critical="yes"></status>
</test>
<doc>Casos de Prueba Proyecto SINAMOPE</doc>
<status status="PASS" starttime="20200714 22:11:54.806" endtime="20200714 22:11:54.821"></status>
</suite>
<suite id="s1-s4" name="Sinamope4" source="C:\TEST_SINAMOPE\TEST\sinamope4.robot">
<test id="s1-s4-t1" name="CC001 SINAMOPE (SISTEMA SINAMOPE)(DESCARGAR REPORTE PDF)">
<kw name="No Operation" library="BuiltIn">
<doc>Does absolutely nothing.</doc>
<status status="NOT_RUN" starttime="20200714 22:11:54.839" endtime="20200714 22:11:54.839"></status>
</kw>
<doc>PRUEBA SINAMOPE 001 (DESCARGAR REPORTE PDF)</doc>
<tags>
<tag>s001</tag>
</tags>
<status status="PASS" starttime="20200714 22:11:54.839" endtime="20200714 22:11:54.839" critical="yes"></status>
</test>
<doc>Casos de Prueba Proyecto SINAMOPE</doc>
<status status="PASS" starttime="20200714 22:11:54.822" endtime="20200714 22:11:54.839"></status>
</suite>
<suite id="s1-s5" name="Sinamope5" source="C:\TEST_SINAMOPE\TEST\sinamope5.robot">
<test id="s1-s5-t1" name="CC001 SINAMOPE (SISTEMA SINAMOPE)(DESCARGAR REPORTE PDF)">
<kw name="No Operation" library="BuiltIn">
<doc>Does absolutely nothing.</doc>
<status status="NOT_RUN" starttime="20200714 22:11:54.848" endtime="20200714 22:11:54.848"></status>
</kw>
<doc>PRUEBA SINAMOPE 001 (DESCARGAR REPORTE PDF)</doc>
<tags>
<tag>s001</tag>
</tags>
<status status="PASS" starttime="20200714 22:11:54.848" endtime="20200714 22:11:54.848" critical="yes"></status>
</test>
<doc>Casos de Prueba Proyecto SINAMOPE</doc>
<status status="PASS" starttime="20200714 22:11:54.839" endtime="20200714 22:11:54.848"></status>
</suite>
<status status="PASS" starttime="20200714 22:11:53.578" endtime="20200714 22:11:54.858"></status>
</suite>
<statistics>
<total>
<stat pass="5" fail="0">Critical Tests</stat>
<stat pass="5" fail="0">All Tests</stat>
</total>
<tag>
<stat pass="5" fail="0">s001</stat>
</tag>
<suite>
<stat pass="5" fail="0" id="s1" name="Suites">Suites</stat>
<stat pass="1" fail="0" id="s1-s1" name="Sinamope">Suites.Sinamope</stat>
<stat pass="1" fail="0" id="s1-s2" name="Sinamope2">Suites.Sinamope2</stat>
<stat pass="1" fail="0" id="s1-s3" name="Sinamope3">Suites.Sinamope3</stat>
<stat pass="1" fail="0" id="s1-s4" name="Sinamope4">Suites.Sinamope4</stat>
<stat pass="1" fail="0" id="s1-s5" name="Sinamope5">Suites.Sinamope5</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200714 22:11:54.395" level="ERROR">Error in file 'C:\TEST_SINAMOPE\TEST\recursos.robot': Importing test library 'C:\TEST_SINAMOPE\TEST\ReadData.py' failed: FileNotFoundError: [Errno 2] No such file or directory: 'Datos_sinamope.xlsx'
Traceback (most recent call last):
  File "C:\TEST_SINAMOPE\TEST\ReadData.py", line 3, in &lt;module&gt;
    data=openpyxl.load_workbook("Datos_sinamope.xlsx")
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 313, in load_workbook
    data_only, keep_links)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PYTHONPATH:
  C:\Users\rodrigo.villanueva.c\AppData\Local\Programs\Python\Python37\Scripts
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\python37.zip
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\DLLs
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages</msg>
<msg timestamp="20200714 22:11:54.798" level="ERROR">Error in file 'C:\TEST_SINAMOPE\TEST\recursos.robot': Importing test library 'C:\TEST_SINAMOPE\TEST\ReadData.py' failed: FileNotFoundError: [Errno 2] No such file or directory: 'Datos_sinamope.xlsx'
Traceback (most recent call last):
  File "C:\TEST_SINAMOPE\TEST\ReadData.py", line 3, in &lt;module&gt;
    data=openpyxl.load_workbook("Datos_sinamope.xlsx")
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 313, in load_workbook
    data_only, keep_links)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PYTHONPATH:
  C:\Users\rodrigo.villanueva.c\AppData\Local\Programs\Python\Python37\Scripts
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\python37.zip
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\DLLs
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages</msg>
<msg timestamp="20200714 22:11:54.815" level="ERROR">Error in file 'C:\TEST_SINAMOPE\TEST\recursos.robot': Importing test library 'C:\TEST_SINAMOPE\TEST\ReadData.py' failed: FileNotFoundError: [Errno 2] No such file or directory: 'Datos_sinamope.xlsx'
Traceback (most recent call last):
  File "C:\TEST_SINAMOPE\TEST\ReadData.py", line 3, in &lt;module&gt;
    data=openpyxl.load_workbook("Datos_sinamope.xlsx")
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 313, in load_workbook
    data_only, keep_links)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PYTHONPATH:
  C:\Users\rodrigo.villanueva.c\AppData\Local\Programs\Python\Python37\Scripts
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\python37.zip
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\DLLs
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages</msg>
<msg timestamp="20200714 22:11:54.834" level="ERROR">Error in file 'C:\TEST_SINAMOPE\TEST\recursos.robot': Importing test library 'C:\TEST_SINAMOPE\TEST\ReadData.py' failed: FileNotFoundError: [Errno 2] No such file or directory: 'Datos_sinamope.xlsx'
Traceback (most recent call last):
  File "C:\TEST_SINAMOPE\TEST\ReadData.py", line 3, in &lt;module&gt;
    data=openpyxl.load_workbook("Datos_sinamope.xlsx")
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 313, in load_workbook
    data_only, keep_links)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PYTHONPATH:
  C:\Users\rodrigo.villanueva.c\AppData\Local\Programs\Python\Python37\Scripts
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\python37.zip
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\DLLs
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages</msg>
<msg timestamp="20200714 22:11:54.848" level="ERROR">Error in file 'C:\TEST_SINAMOPE\TEST\recursos.robot': Importing test library 'C:\TEST_SINAMOPE\TEST\ReadData.py' failed: FileNotFoundError: [Errno 2] No such file or directory: 'Datos_sinamope.xlsx'
Traceback (most recent call last):
  File "C:\TEST_SINAMOPE\TEST\ReadData.py", line 3, in &lt;module&gt;
    data=openpyxl.load_workbook("Datos_sinamope.xlsx")
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 313, in load_workbook
    data_only, keep_links)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PYTHONPATH:
  C:\Users\rodrigo.villanueva.c\AppData\Local\Programs\Python\Python37\Scripts
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\python37.zip
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\DLLs
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37
  c:\users\rodrigo.villanueva.c\appdata\local\programs\python\python37\lib\site-packages</msg>
</errors>
</robot>
